# TP2 — Service Kubernetes
# Description : Exposition du Deployment via un Service NodePort
# Permet l'accès depuis l'extérieur du cluster

apiVersion: v1
kind: Service
metadata:
  name: tp2-webapp-service
  namespace: tp2-kubeflow
  labels:
    app: tp2-webapp
    tp: "2"
spec:
  type: NodePort        # Accessible depuis l'extérieur via <NodeIP>:<NodePort>
  selector:
    app: tp2-webapp     # Cible les pods avec ce label
  ports:
    - protocol: TCP
      port: 80          # Port du service (interne au cluster)
      targetPort: 80    # Port du conteneur
      nodePort: 30080   # Port accessible depuis l'extérieur (30000-32767)
